# ==============================================================================
# NGINX Configuration: Redirect WORKPRISE.FR to CLARAGRAM.COM
# ==============================================================================

server {
    listen 80;
    listen [::]:80;
    server_name workprise.fr www.workprise.fr;
    return 301 https://claragram.com$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name agent.workprise.fr;
    return 301 https://agent.claragram.com$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name portal.workprise.fr;
    return 301 https://portal.claragram.com$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name api.workprise.fr;
    return 301 https://api.claragram.com$request_uri;
}
